version = 0.1
[default.deploy.parameters]
stack_name = "tapestry-collection-workflow"
resolve_s3 = true
s3_prefix = "tapestry-collection-workflow"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
no_confirm_changeset = true
no_fail_on_empty_changeset = true
