AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "API Service to expose API endpoints and trigger events for the Ingestion workflow"

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  TapestryEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: tapestryEventBus

  ApiProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ApiProcessor"
      Handler: app.put_event
      Runtime: python3.13
      CodeUri: .
      Policies:
        - Statement:
            - Sid: EventBridgePutEvents
              Effect: Allow
              Action:
                - events:PutEvents
              Resource:
                - !GetAtt TapestryEventBus.Arn
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref TapestryEventBus
          EVENT_DETAIL_TYPE: "collection-request"
          EVENT_SOURCE: "tapestry.collection_service"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /collect
            Method: POST
            RestApiId: !Ref ApiGateway

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
