AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "API Service to expose API endpoints and trigger events for the Analytics workflow"

Resources:
  TapestryEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: tapestryEventBus

  ApiProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.put_event
      Runtime: python3.13
      CodeUri: .
      Policies:
        - Statement:
            - Sid: EventBridgePutEvents
              Effect: Allow
              Action:
                - events:PutEvents
              Resource:
                - !GetAtt TapestryEventBus.Arn
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref TapestryEventBus
          EVENT_DETAIL_TYPE: "similar-videos-request"
          EVENT_SOURCE: "tapestry.apiService"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /similar-videos
            Method: POST

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
