AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Keyword Extraction Workflow


Resources:
  StateMachineLogs:
    Type: AWS::Logs::LogGroup

  ### Lambda Functions ###
  RouteEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: src/route_events/
      Policies: AWSLambdaBasicExecutionRole
  
  ScrapeProductPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: src/scrape_product_page/
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 120

  SummarizeProductDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: src/summarize_product_details/
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 120
      Environment:
        Variables:
          API_KEY: !Sub "{{resolve:secretsmanager:tapestry/APIKey:SecretString:open_ai}}"

  ExtractKeywordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: src/extract_keywords/
      Policies: AWSLambdaBasicExecutionRole

  ### State Machine ###
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./state-machine/validator.asl.json
      DefinitionSubstitutions:
        RouteEventsFunctionArn: !GetAtt RouteEventsFunction.Arn
        ScrapeProductPageFunctionArn: !GetAtt ScrapeProductPageFunction.Arn
        ExtractKeywordsFunctionArn: !GetAtt ExtractKeywordsFunction.Arn
        SummarizeProductDetailsFunctionArn: !GetAtt SummarizeProductDetailsFunction.Arn
      Events:
        Trigger:
          Type: CloudWatchEvent
          Properties:
            EventBusName: !Ref EventBus
            Pattern:
              source:
                - tapestry.apiService
              detail-type:
                - "similar-videos-request"
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogs.Arn
        IncludeExecutionData: true
        Level: ALL

      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref RouteEventsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ScrapeProductPageFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SummarizeProductDetailsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ExtractKeywordsFunction
        - CloudWatchLogsFullAccess

Parameters:
  EventBus:
    Type: String
    Default: tapestryEventBus
    Description: "The name of the EventBridge event bus"

Outputs:
  StateMachineArn:
    Description: "The ARN of the Analytics State Machine"
    Value: !Ref StateMachine
