name: Delete Collection Workflow from AWS

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack --stack-name tapestry-collection-workflow
          
      - name: Wait for stack deletion
        run: |
          aws cloudformation wait stack-delete-complete --stack-name tapestry-collection-workflow
          echo "Stack deletion completed successfully"