name: Delete Collection Workflow from AWS

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      # Install AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Delete the SAM application
      - name: Delete SAM application
        run: |
          sam delete
